#ifndef __SSV_CONF_PARSER_H__
#define __SSV_CONF_PARSER_H__
char const *conf_parser[] = {
"CONFIG_SSV_BUILD_AS_ONE_KO",
"CONFIG_FW_ALIGNMENT_CHECK",
"CONFIG_PLATFORM_SDIO_OUTPUT_TIMING_0",
"__CHECK_ENDIAN__",
"DEBUG",
"SSV_SUPPORT_SSV6006",
"CONFIG_SSV6200_CLI_ENABLE",
"CONFIG_SSV_BUILD_AS_ONE_KO",
"CONFIG_SSV6200_HAS_RX_WORKQUEUE",
"USE_THREAD_RX",
"USE_GENERIC_DECI_TBL",
"CONFIG_SSV_CTL",
"CONFIG_SSV_SMARTLINK",
"HWIF_SDIO_RX_IRQ",
"CONFIG_FW_ALIGNMENT_CHECK",
"CONFIG_STA_BCN_FILTER",
"CONFIG_SDIO_FAVOR_RX",
"HWIF_IGNORE_SAFE_RW_REG",
"CONFIG_HW_SCAN",
"CONFIG_USB_TX_MULTI_URB",
"CONFIG_ENABLE_DBGMSG",
"CONFIG_ENABLE_CLI_DBG_TOOL",
""};
#endif // __SSV_CONF_PARSER_H__
