# linux/arch/arm/mach-anycloud/Makefile
#
# Copyright 2020 Anyka Microelectronics
#
# Licensed under GPLv2

# Core support for all Anyka SoCs

# Machin support
obj-$(CONFIG_MACH_AK37D)	   += mach-ak37d.o
obj-$(CONFIG_MACH_AK37D)	   += ak_l2.o

obj-$(CONFIG_MACH_AK39EV330)	   += mach-ak39ev330.o
obj-$(CONFIG_MACH_AK39EV330)	   += ak_l2.o

obj-$(CONFIG_MACH_AK37E)	+= mach-ak37e.o
obj-$(CONFIG_MACH_AK37E)	+= ak_l2_dual.o
